"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import "bootstrap/dist/css/bootstrap.css";

import { useEffect } from "react";
import { CartProvider } from "./context/CartContext";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    import("bootstrap/dist/js/bootstrap.bundle");
  }, []);

  return (
    <html lang="en" className={inter.variable}>
      <body
        style={{
          display: "flex",
          flexDirection: "column",
          minHeight: "100vh",
          fontFamily: "var(--font-inter), var(--font-sans)",
        }}
      >
        <NavBar />
        
        <CartProvider>
          <main style={{ flex: 1 }}>{children}</main>
        </CartProvider>

        <Footer />
      </body>
    </html>
  );
}
